MegaProject/MegaProject/Models/Market.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MegaProject.Models
{
    public class Market
    {
        [Key]
        public int Market_id { get; set; }

        public string Market_Name { get; set; }

        public bool Market_Status { get; set; }

    }
}

MegaProject/MegaProject/Controllers/MarketsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MegaProject.Models;

namespace MegaProject.Controllers
{
    public class MarketsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Markets
        public ActionResult Index()
        {
            return View(db.Markets.ToList());
        }

        // GET: Markets/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Market market = db.Markets.Find(id);
            if (market == null)
            {
                return HttpNotFound();
            }
            return View(market);
        }

        // GET: Markets/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Markets/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Market_id,Market_Name,Market_Status")] Market market)
        {
            if (ModelState.IsValid)
            {
                market.Market_Status = true;
                db.Markets.Add(market);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(market);
        }

        // GET: Markets/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Market market = db.Markets.Find(id);
            if (market == null)
            {
                return HttpNotFound();
            }
            return View(market);
        }

        // POST: Markets/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Market_id,Market_Name,Market_Status")] Market market)
        {
            if (ModelState.IsValid)
            {
                market.Market_Status = true;
                db.Entry(market).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(market);
        }

        // GET: Markets/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Market market = db.Markets.Find(id);
            if (market == null)
            {
                return HttpNotFound();
            }
            return View(market);
        }

        // POST: Markets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Market market = db.Markets.Find(id);
            market.Market_Status = false;
            //db.Markets.Remove(market);
            db.Entry(market).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MegaProject/MegaProject/Views/Markets/Create.cshtml

@model MegaProject.Models.Market
@using MegaProject.Models

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    ApplicationDbContext db = new ApplicationDbContext();
}

@section Css {
    <!-- DataTables -->
    <link href="~/Content/Admin_content/dist/css/pages/file-upload.css" rel="stylesheet">
    <link href="~/Content/Admin_content/assets/node_modules/datatables/media/css/dataTables.bootstrap4.css" rel="stylesheet">
}

<div class="page-wrapper">
    <div class="container-fluid">
        <!-- ============================================================== -->
        <!-- Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <div class="row page-titles">
            <div class="col-md-5 align-self-center">
                <h4 class="text-themecolor">Add another Market</h4>
            </div>
            <div class="col-md-7 align-self-center text-right">
                <div class="d-flex justify-content-end align-items-center">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="javascript:void(0)">Market</a></li>
                        <li class="breadcrumb-item active">Add Another Market</li>
                    </ol>

                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Add Market Information</h4>


                        @*<form class="form-material m-t-40" action="~/Shares/Create" method="post"  name="form">*@

                        @using (Html.BeginForm("Create", "Markets", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-group">
                                <label>Market Name</label>
                                <input type="text" class="form-control form-control-line" name="Market_Name" placeholder="Enter Market Name" required />
                            </div>
                                @*<div class="form-group">
                                    <label>Market Status</label>
                                    <input type="checkbox" class="form-control" name="Market_Status"  required>
                                </div>*@
                                <div class="form-group">
                                    <div class="col-sm-2"></div>
                                    <div class="col-sm-8">
                                        <div class="col-sm-6">
                                            <input type="submit" name="Submit" value="Submit" class="btn btn-lg btn-success" style="width:100%" />
                                        </div>
                                        <div class="col-sm-6">
                                            <input type="reset" value="Clear" class="btn btn-lg btn-warning" style="width:100%" />
                                        </div>
                                    </div>

                                    <div class="col-sm-2"></div>
                                </div>
                                @*</form>*@
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div>
    @Html.ActionLink("Back to List", "Index")
</div>




MegaProject/MegaProject/Views/Markets/Delete.cshtml
@model MegaProject.Models.Market

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}


<div class="page-wrapper">
    <div class="container-fluid">
        <!-- ============================================================== -->
        <!-- Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <div class="row page-titles">
            <div class="col-md-5 align-self-center">
                <h4 class="text-themecolor"> Markets List</h4>
            </div>
            <div class="col-md-7 align-self-center text-right">
                <div class="d-flex justify-content-end align-items-center">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="javascript:void(0)">Markets List</a></li>
                        <li class="breadcrumb-item active">Markets</li>
                    </ol>
                    @*<button type="button" class="btn btn-info d-none d-lg-block m-l-15"><i class="fa fa-plus-circle"></i> @Html.ActionLink("Create New", "Create")</button>*@
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Market</h4>
                        <hr />
                        <div class="tab-pane" id="settings" role="tabpanel">
                            <div class="card-body">
                                <h3>Are you sure you want to delete this?</h3>
                                <div>
                                    <h4>Market</h4>
                                    <hr />
                                    <dl class="dl-horizontal">
                                        <dt>
                                            <label class="control-label col-md-12">Market Name</label>
                                        </dt>

                                        <dd>
                                            @Html.DisplayFor(model => model.Market_Name)
                                        </dd>

                                           <dt>
                                                <label class="control-label col-md-12">Market Status </label>
                                            </dt>

                                            <dd>
                                                @Html.DisplayFor(model => model.Market_Status)
                                            </dd>

                                    </dl>

                                    @using (Html.BeginForm())
                                    {
                                        @Html.AntiForgeryToken()

                                        <div class="form-actions no-color">
                                            <input type="submit" value="Delete" class="btn btn-default" /> |
                                            @Html.ActionLink("Back to List", "Index")
                                        </div>
                                    }
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


MegaProject/MegaProject/Views/Markets/Edit.cshtml
@model MegaProject.Models.Market

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

@section Css {
    <!-- DataTables -->
    <link href="~/Content/Admin_content/dist/css/pages/file-upload.css" rel="stylesheet">
    <link href="~/Content/Admin_content/assets/node_modules/datatables/media/css/dataTables.bootstrap4.css" rel="stylesheet">
    <link href="~/Content/Admin_content/assets/node_modules/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css" rel="stylesheet">
    <link href="~/Content/Admin_content/assets/node_modules/bootstrap-datepicker/bootstrap-datepicker.min.css" rel="stylesheet" type="text/css" />
}
<div class="page-wrapper">
    <div class="container-fluid">
        <!-- ============================================================== -->
        <!-- Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <div class="row page-titles">
            <div class="col-md-5 align-self-center">
                <h4 class="text-themecolor"> Markets List</h4>
            </div>
            <div class="col-md-7 align-self-center text-right">
                <div class="d-flex justify-content-end align-items-center">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="javascript:void(0)">Markets</a></li>
                        <li class="breadcrumb-item active">Markets List</li>
                    </ol>
                    @*<button type="button" class="btn btn-info d-none d-lg-block m-l-15"><i class="fa fa-plus-circle"></i> @Html.ActionLink("Create New", "Create")</button>*@
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Market</h4>
                        <hr />
                        <div class="tab-pane" id="settings" role="tabpanel">
                            <div class="card-body">
                                @using (Html.BeginForm("Edit", "Markets", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
                                {
                                    @Html.AntiForgeryToken()

                                    <div class="form-horizontal">
                                        <h4>Market</h4>
                                        <hr />
                                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                        @Html.HiddenFor(model => model.Market_id)

                                        <div class="form-group">
                                            <label class="control-label col-md-12">Market Name</label>
                                            <div class="col-md-12">
                                                <input type="text" value="@Model.Market_Name" name="Market_Name" class="form-control form-control-line">
                                            </div>
                                        </div>
                                        @*<div class="form-group">
                                            <label class="control-label col-md-12">Market Status </label>
                                            <div class="col-md-12">
                                                <input type="checkbox" value="@Model.Market_Status" name="Market_Status" class="form-control form-control-line">
                                            </div>
                                        </div>*@
                                        <div class="form-group">
                                            <div class="col-md-12">
                                                <input type="submit" value="Save" name="Edit" class="btn btn-default" />
                                            </div>
                                        </div>
                                    </div>
                                }
                                <div>
                                    @Html.ActionLink("Back to List", "Index")
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

MegaProject/MegaProject/Views/Markets/Index.cshtml
@using MegaProject.Models
@model IEnumerable<MegaProject.Models.Market>


@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    ApplicationDbContext db = new ApplicationDbContext();
}

@section Css {
    <!-- DataTables -->
    <link href="~/Content/Admin_content/dist/css/pages/file-upload.css" rel="stylesheet">
    <link href="~/Content/Admin_content/assets/node_modules/datatables/media/css/dataTables.bootstrap4.css" rel="stylesheet">
}
<div class="page-wrapper">
    <div class="container-fluid">
        <!-- ============================================================== -->
        <!-- Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <div class="row page-titles">
            <div class="col-md-5 align-self-center">
                <h4 class="text-themecolor">Markets List</h4>
            </div>
            <div class="col-md-7 align-self-center text-right">
                <div class="d-flex justify-content-end align-items-center">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="javascript:void(0)">Markets</a></li>
                        <li class="breadcrumb-item active">Markets</li>
                    </ol>
                    <button type="button" class="btn btn-info d-none d-lg-block m-l-15"><i class="fa fa-plus-circle"></i> @Html.ActionLink("Create New", "Create")</button>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Markets</h4>
                        <hr />
                        <h6 class="card-subtitle"></h6>
                        <div class="table-responsive m-t-40">
                            <table id="example23" class="display nowrap table table-hover table-striped table-bordered" cellspacing="0" width="100%">
                                <thead>
                                    <tr>
                                        <th>Market Name</th>
                                        <th>Market Status</th>
                                    </tr>
                                </thead>
                                <tfoot>
                                    <tr>
                                        <th>Market Name</th>
                                        <th>Market Status</th>  
                                        <th>Actions</th>
                                    </tr>
                                </tfoot>
                                <tbody>
                                    @foreach (var item in db.Markets.ToList())
                                    {
                                        <tr>
                                            <td>@item.Market_Name</td>

                                            <td>@item.Market_Status</td>

                                            <td>
                                                @Html.ActionLink("Edit", "Edit", new { id = item.Market_id}) |
                                                @Html.ActionLink("Delete", "Delete", new { id = item.Market_id })
                                            </td>
                                        </tr>
                                    }

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
