MegaProject/MegaProject/Models/Share.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MegaProject.Models
{
    public class Share
    {
    
        [Key]
        public int Share_id { get; set; }

        public decimal Share_Percentage { get; set; }

        //public string Share_Type { get; set; }

        public int Share_Amount { get; set; }

        public int  Share_Code { get; set; }

        public DateTime Share_Date { get; set; }

    }
}

MegaProject/MegaProject/Controllers/SharesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MegaProject.Models;

namespace MegaProject.Controllers
{
    public class SharesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Shares
        public ActionResult Index()
        {
            return View(db.Shares.ToList());
        }

        // GET: Shares/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Share share = db.Shares.Find(id);
            if (share == null)
            {
                return HttpNotFound();
            }
            return View(share);
        }

        // GET: Shares/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Shares/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Share_id,Share_Percentage,/*Share_Type*/,Share_Amount,Share_Code,Share_Date")] Share share)
        {
            if (ModelState.IsValid)
            {
                db.Shares.Add(share);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(share);
        }

        // GET: Shares/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Share share = db.Shares.Find(id);
            if (share == null)
            {
                return HttpNotFound();
            }
            return View(share);
        }

        // POST: Shares/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        //public ActionResult Edit([Bind(Include = "Share_id,Share_Percentage,Share_Type,Share_Amount,Share_Code,Share_Date")] Share share)
        //{
        //    if (ModelState.IsValid)
        //    {
               
        //        db.Entry(share).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    return View(share);
        //}
        public ActionResult Edit(Share share)
        {
            if (ModelState.IsValid)
            {

                Share share_update = db.Shares.Find(share.Share_id);
                share_update.Share_Percentage= share.Share_Percentage;
               // share_update.Share_Type = share.Share_Type;
                share_update.Share_Amount = share.Share_Amount;
                share_update.Share_Code = share.Share_Code;
                share_update.Share_Date = share.Share_Date;
                //appuser.Email = "";
                //var result = await UserManager.UpdateAsync(appuser , )  
                db.Entry(share_update).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(share);
        }

        // GET: Shares/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Share share = db.Shares.Find(id);
            if (share == null)
            {
                return HttpNotFound();
            }
            return View(share);
        }

        // POST: Shares/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Share share = db.Shares.Find(id);
            db.Shares.Remove(share);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

     

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MegaProject/MegaProject/Views/Shares/Create.cshtml
@model MegaProject.Models.Share

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

@section Css {
    <!-- DataTables -->
    <link href="~/Content/Admin_content/dist/css/pages/file-upload.css" rel="stylesheet">
    <link href="~/Content/Admin_content/assets/node_modules/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css" rel="stylesheet">
    <link href="~/Content/Admin_content/assets/node_modules/bootstrap-datepicker/bootstrap-datepicker.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/Admin_content/assets/node_modules/datatables/media/css/dataTables.bootstrap4.css" rel="stylesheet">
}

<div class="page-wrapper">
    <div class="container-fluid">
        <!-- ============================================================== -->
        <!-- Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <div class="row page-titles">
            <div class="col-md-5 align-self-center">
                <h4 class="text-themecolor">Add Share</h4>
            </div>
            <div class="col-md-7 align-self-center text-right">
                <div class="d-flex justify-content-end align-items-center">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="javascript:void(0)">Store</a></li>
                        <li class="breadcrumb-item active">Add Share</li>
                    </ol>

                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Add Share Information</h4>


                        @*<form class="form-material m-t-40" action="~/Shares/Create" method="post"  name="form">*@

                        @using (Html.BeginForm("Create", "Shares", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                        {
                            @Html.AntiForgeryToken()
                            <div class="form-group">
                                <label>Share Percentage</label>
                                <input type="text" class="form-control form-control-line" name="Share_Percentage" placeholder="Enter Share Percentage" required />
                            </div>
                            @*<div class="form-group">
                                <label>Share Type</label>
                                <input type="text" class="form-control form-control-line" name="Share_Type" placeholder="Enter Share Type" required />
                            </div>*@
                            <div class="form-group">
                                <label>Share Amount</label>
                                <input type="number" class="form-control form-control-line" name="Share_Amount" placeholder="Enter Share Amount" required />
                            </div>
                            <div class="form-group">
                                <label>Share Code</label>
                                <input type="text" class="form-control form-control-line" name="Share_Code" placeholder="Enter Share Code" required />
                            </div>
                            <div class="form-group">
                                <label>Share Creation Date</label>
                                <input type="text" class="form-control" name="Share_Date" placeholder="2017-06-04" id="mdate">
                                </div>

                            <div class="form-group">
                                <div class="col-sm-2"></div>
                                <div class="col-sm-8">
                                    <div class="col-sm-6">
                                        <input type="submit" name="Submit" value="Submit" class="btn btn-lg btn-success" style="width:100%" />
                                    </div>
                                    <div class="col-sm-6">
                                        <input type="reset" value="Clear" class="btn btn-lg btn-warning" style="width:100%" />
                                    </div>
                                </div>

                                <div class="col-sm-2"></div>
                            </div>
                            @*</form>*@
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts{
    <script src="~/Content/Admin_content/assets/node_modules/moment/moment.js"></script>
    <script src="~/Content/Admin_content/assets/node_modules/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js"></script>
    <script src="~/Content/Admin_content/assets/node_modules/bootstrap-datepicker/bootstrap-datepicker.min.js"></script>
    <script src="~/Content/Admin_content/assets/node_modules/timepicker/bootstrap-timepicker.min.js"></script>
    <script src="~/Content/Admin_content/assets/node_modules/bootstrap-daterangepicker/daterangepicker.js"></script>
    <script>
        // MAterial Date picker
        $('#mdate').bootstrapMaterialDatePicker({ format: 'MM/DD/YYYY HH:mm', weekStart: 0, time: false });
        $('#timepicker').bootstrapMaterialDatePicker({ format: 'HH:mm', time: true, date: false });
        $('#date-format').bootstrapMaterialDatePicker({ format: 'dddd DD MMMM YYYY - HH:mm' });

        $('#min-date').bootstrapMaterialDatePicker({ format: 'DD/MM/YYYY HH:mm', minDate: new Date() });
        // Clock pickers
        $('#single-input').clockpicker({
            placement: 'bottom',
            align: 'left',
            autoclose: true,
            'default': 'now'
        });
        $('.clockpicker').clockpicker({
            donetext: 'Done',
        }).find('input').change(function () {
            console.log(this.value);
        });
        $('#check-minutes').click(function (e) {
            // Have to stop propagation here
            e.stopPropagation();
            input.clockpicker('show').clockpicker('toggleView', 'minutes');
        });
        if (/mobile/i.test(navigator.userAgent)) {
            $('input').prop('readOnly', true);
        }
        // Colorpicker
        $(".colorpicker").asColorPicker();
        $(".complex-colorpicker").asColorPicker({
            mode: 'complex'
        });
        $(".gradient-colorpicker").asColorPicker({
            mode: 'gradient'
        });
        // Date Picker
        jQuery('.mydatepicker, #datepicker').datepicker();
        jQuery('#datepicker-autoclose').datepicker({
            autoclose: true,
            todayHighlight: true
        });
        jQuery('#date-range').datepicker({
            toggleActive: true
        });
        jQuery('#datepicker-inline').datepicker({
            todayHighlight: true
        });
        // Daterange picker
        $('.input-daterange-datepicker').daterangepicker({
            buttonClasses: ['btn', 'btn-sm'],
            applyClass: 'btn-danger',
            cancelClass: 'btn-inverse'
        });
        $('.input-daterange-timepicker').daterangepicker({
            timePicker: true,
            format: 'MM/DD/YYYY h:mm A',
            timePickerIncrement: 30,
            timePicker12Hour: true,
            timePickerSeconds: false,
            buttonClasses: ['btn', 'btn-sm'],
            applyClass: 'btn-danger',
            cancelClass: 'btn-inverse'
        });
        $('.input-limit-datepicker').daterangepicker({
            format: 'MM/DD/YYYY',
            minDate: '06/01/2015',
            maxDate: '06/30/2015',
            buttonClasses: ['btn', 'btn-sm'],
            applyClass: 'btn-danger',
            cancelClass: 'btn-inverse',
            dateLimit: {
                days: 6
            }
        });
    </script>
}

MegaProject/MegaProject/Views/Shares/Delete.cshtml
@model MegaProject.Models.Share

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

@section Css {
    <!-- DataTables -->
    <link href="~/Content/Admin_content/dist/css/pages/file-upload.css" rel="stylesheet">
    <link href="~/Content/Admin_content/assets/node_modules/datatables/media/css/dataTables.bootstrap4.css" rel="stylesheet">
}


<div class="page-wrapper">
    <div class="container-fluid">
        <!-- ============================================================== -->
        <!-- Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <div class="row page-titles">
            <div class="col-md-5 align-self-center">
                <h4 class="text-themecolor"> ShareHolders List</h4>
            </div>
            <div class="col-md-7 align-self-center text-right">
                <div class="d-flex justify-content-end align-items-center">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="javascript:void(0)">Share Holders</a></li>
                        <li class="breadcrumb-item active">Share Holders</li>
                    </ol>
                    @*<button type="button" class="btn btn-info d-none d-lg-block m-l-15"><i class="fa fa-plus-circle"></i> @Html.ActionLink("Create New", "Create")</button>*@
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Store</h4>
                        <hr />
                        <div class="tab-pane" id="settings" role="tabpanel">
                            <div class="card-body">
                                <h3>Are you sure you want to delete this?</h3>
                                <div>
                                    <h4>Share</h4>
                                    <hr />
                                    <dl class="dl-horizontal">
                                        <dt>
                                            <label class="control-label col-md-12">Share Percentage</label>
                                        </dt>

                                        <dd>
                                            @Html.DisplayFor(model => model.Share_Percentage)
                                        </dd>

                                        @*<dt>
                                            <label class="control-label col-md-12">Share Type </label>
                                        </dt>

                                        <dd>
                                            @Html.DisplayFor(model => model.Share_Type)
                                        </dd>*@

                                        <dt>
                                            <label class="control-label col-md-12">Share Amount</label>
                                        </dt>

                                        <dd>
                                            @Html.DisplayFor(model => model.Share_Amount)
                                        </dd>

                                        <dt>
                                            <label class="control-label col-md-12">Share Code </label>
                                        </dt>

                                        <dd>
                                            @Html.DisplayFor(model => model.Share_Code)
                                        </dd>

                                        @*<dt>
                                            <label class="control-label col-md-12">Share Date </label>
                                        </dt>

                                        <dd>
                                            @Html.DisplayFor(model => model.Share_Date)
                                        </dd>*@

                                    </dl>

                                    @using (Html.BeginForm())
                                    {
                                        @Html.AntiForgeryToken()

                                        <div class="form-actions no-color">
                                            <input type="submit" value="Delete" class="btn btn-default" /> |
                                            @Html.ActionLink("Back to List", "Index")
                                        </div>
                                    }
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


MegaProject/MegaProject/Views/Shares/Edit.cshtml
@model MegaProject.Models.Share

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

@section Css {
    <!-- DataTables -->
    <link href="~/Content/Admin_content/dist/css/pages/file-upload.css" rel="stylesheet">
    <link href="~/Content/Admin_content/assets/node_modules/datatables/media/css/dataTables.bootstrap4.css" rel="stylesheet">
<link href="~/Content/Admin_content/assets/node_modules/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css" rel="stylesheet">
<link href="~/Content/Admin_content/assets/node_modules/bootstrap-datepicker/bootstrap-datepicker.min.css" rel="stylesheet" type="text/css" />
}
<div class="page-wrapper">
    <div class="container-fluid">
        <!-- ============================================================== -->
        <!-- Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <div class="row page-titles">
            <div class="col-md-5 align-self-center">
                <h4 class="text-themecolor"> ShareHolders List</h4>
            </div>
            <div class="col-md-7 align-self-center text-right">
                <div class="d-flex justify-content-end align-items-center">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="javascript:void(0)">Share Holders</a></li>
                        <li class="breadcrumb-item active">Share Holders</li>
                    </ol>
                    @*<button type="button" class="btn btn-info d-none d-lg-block m-l-15"><i class="fa fa-plus-circle"></i> @Html.ActionLink("Create New", "Create")</button>*@
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body"> 
                        <h4 class="card-title">Store</h4>
                        <hr />
                        <div class="tab-pane" id="settings" role="tabpanel">
                            <div class="card-body">
                                 @using (Html.BeginForm("Edit" ,"Shares" , FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
                                  { 
                                     @Html.AntiForgeryToken()   
                                     
                                     <div class="form-horizontal">
                                    <h4>Share</h4>
                                    <hr />
                                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                    @Html.HiddenFor(model => model.Share_id)

                                         <div class="form-group">
                                             <label class="control-label col-md-12">Share Percentage</label>
                                             <div class="col-md-12">
                                                 <input type="text" value="@Model.Share_Percentage" name="Share_Percentage" class="form-control form-control-line">
                                             </div>
                                         </div>                    
                                         @*<div class="form-group">
                                             <label class="control-label col-md-12">Share Type </label>
                                             <div class="col-md-12">
                                                 <input type="text" value="@Model.Share_Type" name="Share_Type" class="form-control form-control-line">
                                             </div>
                                         </div>*@   
                                         <div class="form-group">
                                             <label class="control-label col-md-12">Share Amount </label>
                                             <div class="col-md-12">
                                                 <input type="text" value="@Model.Share_Amount" name="Share_Amount" class="form-control form-control-line">
                                             </div>
                                         </div>   
                                         <div class="form-group">
                                             <label class="control-label col-md-12">Share Code</label>
                                             <div class="col-md-12">
                                                 <input type="text" value="@Model.Share_Code" name="Share_Code" class="form-control form-control-line">
                                             </div>
                                         </div>   
                                         <div class="form-group">
                                             <label class="control-label col-md-12">Share Creation Date </label>
                                             <div class="col-md-12">
                                                 <input type="text"  value="@Model.Share_Date.ToShortDateString()"  class="form-control" name="Share_Date" placeholder="2017-06-04" id="mdate">
                                                
                                             </div>
                                         </div>   

                                    <div class="form-group">
                                        <div class="col-md-12">
                                            <input type="submit" value="Save" name="Edit"  class="btn btn-default" />
                                        </div>
                                    </div>
                            </div>
                            }
                            <div>
                                @Html.ActionLink("Back to List", "Index")
                            </div>
                            </div>
                        </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@section Scripts{
    <script src="~/Content/Admin_content/assets/node_modules/moment/moment.js"></script>
    <script src="~/Content/Admin_content/assets/node_modules/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js"></script>
    <script src="~/Content/Admin_content/assets/node_modules/bootstrap-datepicker/bootstrap-datepicker.min.js"></script>
    <script src="~/Content/Admin_content/assets/node_modules/timepicker/bootstrap-timepicker.min.js"></script>
    <script src="~/Content/Admin_content/assets/node_modules/bootstrap-daterangepicker/daterangepicker.js"></script>
    <script>
        // MAterial Date picker
        $('#mdate').bootstrapMaterialDatePicker({ format: 'MM/DD/YYYY HH:mm', weekStart: 0, time: false });
        $('#timepicker').bootstrapMaterialDatePicker({ format: 'HH:mm', time: true, date: false });
        $('#date-format').bootstrapMaterialDatePicker({ format: 'dddd DD MMMM YYYY - HH:mm' });

        $('#min-date').bootstrapMaterialDatePicker({ format: 'DD/MM/YYYY HH:mm', minDate: new Date() });
        // Clock pickers
        $('#single-input').clockpicker({
            placement: 'bottom',
            align: 'left',
            autoclose: true,
            'default': 'now'
        });
        $('.clockpicker').clockpicker({
            donetext: 'Done',
        }).find('input').change(function () {
            console.log(this.value);
        });
        $('#check-minutes').click(function (e) {
            // Have to stop propagation here
            e.stopPropagation();
            input.clockpicker('show').clockpicker('toggleView', 'minutes');
        });
        if (/mobile/i.test(navigator.userAgent)) {
            $('input').prop('readOnly', true);
        }
        // Colorpicker
        $(".colorpicker").asColorPicker();
        $(".complex-colorpicker").asColorPicker({
            mode: 'complex'
        });
        $(".gradient-colorpicker").asColorPicker({
            mode: 'gradient'
        });
        // Date Picker
        jQuery('.mydatepicker, #datepicker').datepicker();
        jQuery('#datepicker-autoclose').datepicker({
            autoclose: true,
            todayHighlight: true
        });
        jQuery('#date-range').datepicker({
            toggleActive: true
        });
        jQuery('#datepicker-inline').datepicker({
            todayHighlight: true
        });
        // Daterange picker
        $('.input-daterange-datepicker').daterangepicker({
            buttonClasses: ['btn', 'btn-sm'],
            applyClass: 'btn-danger',
            cancelClass: 'btn-inverse'
        });
        $('.input-daterange-timepicker').daterangepicker({
            timePicker: true,
            format: 'MM/DD/YYYY h:mm A',
            timePickerIncrement: 30,
            timePicker12Hour: true,
            timePickerSeconds: false,
            buttonClasses: ['btn', 'btn-sm'],
            applyClass: 'btn-danger',
            cancelClass: 'btn-inverse'
        });
        $('.input-limit-datepicker').daterangepicker({
            format: 'MM/DD/YYYY',
            minDate: '06/01/2015',
            maxDate: '06/30/2015',
            buttonClasses: ['btn', 'btn-sm'],
            applyClass: 'btn-danger',
            cancelClass: 'btn-inverse',
            dateLimit: {
                days: 6
            }
        });
    </script>
    }