MegaProject/MegaProject/Models/Share_Holder.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MegaProject.Models
{
    public class Share_Holder
    {
        [Key]
        public int Share_Holder_id { get; set; }

        public string Id { get; set; }
        public virtual ApplicationUser ApplicationUser { get; set; }

        public int Share_History_id { get; set; }
        public virtual Share_History Share_History { get; set; }

        public string Share_Holder_Name{ get; set; }

        public string Share_Holder_UniqueId { get; set; }

        public string Share_Holder_Password { get; set; }

        public DateTime Share_Holder_Date { get; set; }


    }
}

MegaProject/MegaProject/Controllers/Share_HoldersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MegaProject.Models;

namespace MegaProject.Controllers
{
    public class Share_HoldersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Share_Holders
        public ActionResult Index()
        {
            var share_Holders = db.Share_Holders.Include(s => s.ApplicationUser).Include(s => s.Share_History);
            return View(share_Holders.ToList());
        }

        // GET: Share_Holders/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Share_Holder share_Holder = db.Share_Holders.Find(id);
            if (share_Holder == null)
            {
                return HttpNotFound();
            }
            return View(share_Holder);
        }

        // GET: Share_Holders/Create
        public ActionResult Create()
        {
            
         //   ViewBag.Share_History_id = new SelectList(db.Share_Histories, "Share_History_id", "Share_History_id");
            return View();
        }

        // POST: Share_Holders/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Share_Holder_id,Id,Share_History_id,Share_Holder_Name,Share_Holder_UniqueId,Share_Holder_Password,Share_Holder_Date")] Share_Holder share_Holder)
        {
            if (ModelState.IsValid)
            {
                //string userId = "";
                //userId = Session["usrnamw"].ToString(); 
                db.Share_Holders.Add(share_Holder);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

          
            ViewBag.Share_History_id = new SelectList(db.Share_Histories, "Share_History_id", "Share_History_id", share_Holder.Share_History_id);
            return View(share_Holder);
        }

        // GET: Share_Holders/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Share_Holder share_Holder = db.Share_Holders.Find(id);
            if (share_Holder == null)
            {
                return HttpNotFound();
            }
         
            ViewBag.Share_History_id = new SelectList(db.Share_Histories, "Share_History_id", "Share_History_id", share_Holder.Share_History_id);
            return View(share_Holder);
        }

        // POST: Share_Holders/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Share_Holder share_Holder)
        {
            if (ModelState.IsValid)
            {
                Share_Holder share_holder_update = db.Share_Holders.Find(share_Holder.Share_Holder_id);
                share_holder_update.Share_History_id = share_Holder.Share_History_id;
                share_holder_update.Share_Holder_Name = share_Holder.Share_Holder_Name;
                share_holder_update.Share_Holder_UniqueId = share_Holder.Share_Holder_UniqueId;
                share_holder_update.Share_Holder_Password = share_Holder.Share_Holder_Password;
                share_holder_update.Share_Holder_Date = share_Holder.Share_Holder_Date;

                db.Entry(share_holder_update).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(share_Holder);
        }

        // GET: Share_Holders/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Share_Holder share_Holder = db.Share_Holders.Find(id);
            if (share_Holder == null)
            {
                return HttpNotFound();
            }
            return View(share_Holder);
        }

        // POST: Share_Holders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Share_Holder share_Holder = db.Share_Holders.Find(id);
            db.Share_Holders.Remove(share_Holder);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Shareinfo()
        {
            return View();
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MegaProject/MegaProject/Views/Share_Holders/Create.cshtml

@model MegaProject.Models.Share_Holder
@using MegaProject.Models

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    ApplicationDbContext db = new ApplicationDbContext();
}



@section Css {
    <!-- DataTables -->
    <link href="~/Content/Admin_content/dist/css/pages/file-upload.css" rel="stylesheet">

    <link href="~/Content/Admin_content/assets/node_modules/datatables/media/css/dataTables.bootstrap4.css" rel="stylesheet">
    <link href="~/Content/Admin_content/assets/node_modules/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css" rel="stylesheet">
    <link href="~/Content/Admin_content/assets/node_modules/bootstrap-datepicker/bootstrap-datepicker.min.css" rel="stylesheet" type="text/css" />


}
<div class="page-wrapper">
    <div class="container-fluid">
        <!-- ============================================================== -->
        <!-- Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <div class="row page-titles">
            <div class="col-md-5 align-self-center">
                <h4 class="text-themecolor">Add Share</h4>
            </div>
            <div class="col-md-7 align-self-center text-right">
                <div class="d-flex justify-content-end align-items-center">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="javascript:void(0)">Store</a></li>
                        <li class="breadcrumb-item active">Add Share Holder</li>
                    </ol>

                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Add Share Holder's Information</h4>


                        @*<form class="form-material m-t-40" action="~/Shares/Create" method="post"  name="form">*@

                        @using (Html.BeginForm("RegisterShare", "Account", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-group">
                                <label>Share Holder Type</label>
                                <select class="form-control" name="RoleName">
                                    <option value="EmployeeShareHolder">Employee</option>
                                    <option value="ShareHolder">External</option>
                                </select>
                                <div class="form-group">
                                    <label>Share Percentage</label>
                                    <select class="form-control" name="Share_History_id">
                                        @{

                                            var on_amount = db.Share_Histories.Where(x => x.Share.Share_Code== 1).ToList().AsEnumerable().Select(x => x.Share.Share_Percentage).LastOrDefault();
                                            var on_actual_amount = db.Share_Histories.Where(x => x.Share.Share_Code == 1).AsEnumerable().Select(x => x.Share_History_Amount).LastOrDefault();
                                            var on_value = db.Share_Histories.Where(x => x.Share.Share_Code == 1).ToList().AsEnumerable().Select(x => x.Share_History_id).LastOrDefault();

                                            var fi_amount = db.Share_Histories.Where(x => x.Share.Share_Code == 5).ToList().AsEnumerable().Select(x => x.Share.Share_Percentage).LastOrDefault();
                                            var fi_actual_amount = db.Share_Histories.Where(x => x.Share.Share_Code== 5).AsEnumerable().Select(x => x.Share_History_Amount).LastOrDefault();
                                            var fi_value = db.Share_Histories.Where(x => x.Share.Share_Code == 5).ToList().AsEnumerable().Select(x => x.Share_History_id).LastOrDefault();

                                            var te_amount = db.Share_Histories.Where(x => x.Share.Share_Code == 10).ToList().AsEnumerable().Select(x => x.Share.Share_Percentage).LastOrDefault();
                                            var te_actual_amount = db.Share_Histories.Where(x => x.Share.Share_Code == 10).AsEnumerable().Select(x => x.Share_History_Amount).LastOrDefault();
                                            var te_value = db.Share_Histories.Where(x => x.Share.Share_Code == 10).ToList().AsEnumerable().Select(x => x.Share_History_id).LastOrDefault();
                                        }

                                        <option value="@on_value">@on_amount (Rs @on_actual_amount)     </option>
                                        <option value="@fi_value">@fi_amount (Rs @fi_actual_amount)      </option>
                                        <option value="@te_value">@te_amount (Rs @te_actual_amount )     </option>

                                    </select>

                                    <div class="form-group">
                                        <label>Share Holder's Name</label>
                                        <input type="text" class="form-control form-control-line" name="Share_Holder_Name" placeholder="Enter Share Holder's Name'" required />
                                    </div>
                                    <div class="form-group">
                                        <label>Share Holder's Unique ID</label>
                                        <input type="text" class="form-control form-control-line" name="Share_Holder_UniqueId" placeholder="Enter Share Holders Unique ID" required />
                                    </div>
                                    <div class="form-group">
                                        <label>Share Holder's Password</label>
                                        <input type="text" class="form-control form-control-line" name="Share_Holder_Password" placeholder="Enter Share Holder's' Code" required />
                                    </div>
                                    <div class="form-group">
                                        <label>Share Holder Date</label>
                                    
                                        <input type="text" class="form-control" name="Share_Holder_Date" placeholder="2017-06-04" id="mdate">
                                        @*<input type="date" class="form-control form-control-line" name="Share_Holder_Date" placeholder="Enter Share Holder's Date" required />*@
                                    </div>

                                    <div class="form-group">
                                        <div class="col-sm-2"></div>
                                        <div class="col-sm-8">
                                            <div class="col-sm-6">
                                                <input type="submit" name="Submit" value="Submit" class="btn btn-lg btn-success" style="width:100%" />
                                            </div>
                                            <div class="col-sm-6">
                                                <input type="reset" value="Clear" class="btn btn-lg btn-warning" style="width:100%" />
                                            </div>
                                        </div>

                                        <div class="col-sm-2"></div>
                                    </div>
                                    @*</form>*@

                                </div>
                            </div>
                                            }

                    </div>
                </div>
            </div>
        </div>
        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>
    </div>
</div>


@section Scripts{
    <script src="~/Content/Admin_content/assets/node_modules/moment/moment.js"></script>
    <script src="~/Content/Admin_content/assets/node_modules/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js"></script>
    <script src="~/Content/Admin_content/assets/node_modules/bootstrap-datepicker/bootstrap-datepicker.min.js"></script>
    <script src="~/Content/Admin_content/assets/node_modules/timepicker/bootstrap-timepicker.min.js"></script>
    <script src="~/Content/Admin_content/assets/node_modules/bootstrap-daterangepicker/daterangepicker.js"></script>
    <script>
        // MAterial Date picker
        $('#mdate').bootstrapMaterialDatePicker({ format: 'MM/DD/YYYY HH:mm', weekStart: 0, time: false });
        $('#timepicker').bootstrapMaterialDatePicker({ format: 'HH:mm', time: true, date: false });
        $('#date-format').bootstrapMaterialDatePicker({ format: 'dddd DD MMMM YYYY - HH:mm' });

        $('#min-date').bootstrapMaterialDatePicker({ format: 'DD/MM/YYYY HH:mm', minDate: new Date() });
        // Clock pickers
        $('#single-input').clockpicker({
            placement: 'bottom',
            align: 'left',
            autoclose: true,
            'default': 'now'
        });
        $('.clockpicker').clockpicker({
            donetext: 'Done',
        }).find('input').change(function () {
            console.log(this.value);
        });
        $('#check-minutes').click(function (e) {
            // Have to stop propagation here
            e.stopPropagation();
            input.clockpicker('show').clockpicker('toggleView', 'minutes');
        });
        if (/mobile/i.test(navigator.userAgent)) {
            $('input').prop('readOnly', true);
        }
        // Colorpicker
        $(".colorpicker").asColorPicker();
        $(".complex-colorpicker").asColorPicker({
            mode: 'complex'
        });
        $(".gradient-colorpicker").asColorPicker({
            mode: 'gradient'
        });
        // Date Picker
        jQuery('.mydatepicker, #datepicker').datepicker();
        jQuery('#datepicker-autoclose').datepicker({
            autoclose: true,
            todayHighlight: true
        });
        jQuery('#date-range').datepicker({
            toggleActive: true
        });
        jQuery('#datepicker-inline').datepicker({
            todayHighlight: true
        });
        // Daterange picker
        $('.input-daterange-datepicker').daterangepicker({
            buttonClasses: ['btn', 'btn-sm'],
            applyClass: 'btn-danger',
            cancelClass: 'btn-inverse'
        });
        $('.input-daterange-timepicker').daterangepicker({
            timePicker: true,
            format: 'MM/DD/YYYY h:mm A',
            timePickerIncrement: 30,
            timePicker12Hour: true,
            timePickerSeconds: false,
            buttonClasses: ['btn', 'btn-sm'],
            applyClass: 'btn-danger',
            cancelClass: 'btn-inverse'
        });
        $('.input-limit-datepicker').daterangepicker({
            format: 'MM/DD/YYYY',
            minDate: '06/01/2015',
            maxDate: '06/30/2015',
            buttonClasses: ['btn', 'btn-sm'],
            applyClass: 'btn-danger',
            cancelClass: 'btn-inverse',
            dateLimit: {
                days: 6
            }
        });
    </script>

}


































MegaProject/MegaProject/Views/Share_Holders/Details.cshtml
@model MegaProject.Models.Share_Holder

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Share_Holder</h4>
    <hr />
    <dl class="dl-horizontal">
        @*<dt>
            @Html.DisplayNameFor(model => model.ApplicationUser.UserRole)
        </dt>*@

        @*<dd>
            @Html.DisplayFor(model => model.ApplicationUser.UserRole)
        </dd>*@

        <dt>
            @Html.DisplayNameFor(model => model.Share_History.Share_History_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Share_History.Share_History_id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Share_Holder_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Share_Holder_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Share_Holder_UniqueId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Share_Holder_UniqueId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Share_Holder_Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Share_Holder_Password)
        </dd>

    

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Share_Holder_id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MegaProject/MegaProject/Views/Share_Holders/Edit.cshtml

@model MegaProject.Models.Share_Holder
@using MegaProject.Models

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    ApplicationDbContext db = new ApplicationDbContext();
}
@section Css {
    <!-- DataTables -->
    <link href="~/Content/Admin_content/dist/css/pages/file-upload.css" rel="stylesheet">

    <link href="~/Content/Admin_content/assets/node_modules/datatables/media/css/dataTables.bootstrap4.css" rel="stylesheet">
<link href="~/Content/Admin_content/assets/node_modules/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css" rel="stylesheet">
<link href="~/Content/Admin_content/assets/node_modules/bootstrap-datepicker/bootstrap-datepicker.min.css" rel="stylesheet" type="text/css" />
}

<div class="page-wrapper">
    <div class="container-fluid">
        <!-- ============================================================== -->
        <!-- Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <div class="row page-titles">
            <div class="col-md-5 align-self-center">
                <h4 class="text-themecolor">Add Share</h4>
            </div>
            <div class="col-md-7 align-self-center text-right">
                <div class="d-flex justify-content-end align-items-center">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="javascript:void(0)">Store</a></li>
                        <li class="breadcrumb-item active">Edit Share Holder</li>
                    </ol>

                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Add Share Holder's Information</h4>


                        @*<form class="form-material m-t-40" action="~/Shares/Create" method="post"  name="form">*@

                        @using (Html.BeginForm("Edit", "Share_Holders", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
                        {
                            @Html.AntiForgeryToken()
                            @Html.HiddenFor(model => model.Share_Holder_id)
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                            <div class="form-group">
                                <label>Share Holder Type</label>
                                <select class="form-control" name="RoleName">
                                    <option value="temp">Employee</option>
                                    <option value="ShareHolder">External</option>
                                </select>
                                <div class="form-group">
                                    <label>Share Percentage</label>
                                    <select class="form-control" name="Share_History_id">
                                        @{
                                            var on_amount = db.Share_Histories.Where(x => x.Share.Share_Code == 1).ToList().AsEnumerable().Select(x => x.Share.Share_Percentage).LastOrDefault();
                                            var on_actual_amount = db.Share_Histories.Where(x => x.Share.Share_Code == 1).AsEnumerable().Select(x => x.Share_History_Amount).LastOrDefault();
                                            var on_value = db.Share_Histories.Where(x => x.Share.Share_Code == 1).ToList().AsEnumerable().Select(x => x.Share_History_id).LastOrDefault();

                                            var fi_amount = db.Share_Histories.Where(x => x.Share.Share_Code == 5).ToList().AsEnumerable().Select(x => x.Share.Share_Percentage).LastOrDefault();
                                            var fi_actual_amount = db.Share_Histories.Where(x => x.Share.Share_Code == 5).AsEnumerable().Select(x => x.Share_History_Amount).LastOrDefault();
                                            var fi_value = db.Share_Histories.Where(x => x.Share.Share_Code == 5).ToList().AsEnumerable().Select(x => x.Share_History_id).LastOrDefault();

                                            var te_amount = db.Share_Histories.Where(x => x.Share.Share_Code == 10).ToList().AsEnumerable().Select(x => x.Share.Share_Percentage).LastOrDefault();
                                            var te_actual_amount = db.Share_Histories.Where(x => x.Share.Share_Code == 10).AsEnumerable().Select(x => x.Share_History_Amount).LastOrDefault();
                                            var te_value = db.Share_Histories.Where(x => x.Share.Share_Code == 10).ToList().AsEnumerable().Select(x => x.Share_History_id).LastOrDefault();
                                        }

                                        <option value="@on_value">@on_amount (Rs @on_actual_amount)     </option>
                                        <option value="@fi_value">@fi_amount (Rs @fi_actual_amount)      </option>
                                        <option value="@te_value">@te_amount (Rs @te_actual_amount)     </option>

                                    </select>

                                    <div class="form-group">
                                        <label>Share Holder's Name</label>
                                        <input type="text" value="@Model.Share_Holder_Name"  class="form-control form-control-line" name="Share_Holder_Name" placeholder="Enter Share Holder's Name'" required />
                                    </div>
                                    <div class="form-group">
                                        <label>Share Holder's Unique ID</label>
                                        <input type="text" value="@Model.Share_Holder_UniqueId" class="form-control form-control-line" name="Share_Holder_UniqueId" placeholder="Enter Share Holders Unique ID" required />
                                    </div>
                                    <div class="form-group">
                                        <label>Share Holder's Password</label>
                                        <input type="text" value="@Model.Share_Holder_Password" class="form-control form-control-line" name="Share_Holder_Password" placeholder="Enter Share Holder's' Code" required />
                                    </div>
                                    <div class="form-group">
                                        <label>Share Holder Date</label>
                                        <input type="text" class="form-control" value="@Model.Share_Holder_Date.ToShortDateString()" name="Share_Holder_Date" placeholder="2017-06-04" id="mdate">
                                       
                                    </div>
                                    <div class="form-group">
                                        <div class="col-md-12">
                                            <input type="submit" value="Save" name="Edit" class="btn btn-default" />
                                        </div>
                                    </div>
                                </div>
                                @*</form>*@
                            </div>
                                            }
                    </div>
                </div>
            </div>
        </div>
        <div>
        </div>
    </div>
</div>



@section Scripts{
    <script src="~/Content/Admin_content/assets/node_modules/moment/moment.js"></script>
    <script src="~/Content/Admin_content/assets/node_modules/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js"></script>
    <script src="~/Content/Admin_content/assets/node_modules/bootstrap-datepicker/bootstrap-datepicker.min.js"></script>
    <script src="~/Content/Admin_content/assets/node_modules/timepicker/bootstrap-timepicker.min.js"></script>
    <script src="~/Content/Admin_content/assets/node_modules/bootstrap-daterangepicker/daterangepicker.js"></script>
    <script>
        // MAterial Date picker
        $('#mdate').bootstrapMaterialDatePicker({ format: 'MM/DD/YYYY HH:mm', weekStart: 0, time: false });
        $('#timepicker').bootstrapMaterialDatePicker({ format: 'HH:mm', time: true, date: false });
        $('#date-format').bootstrapMaterialDatePicker({ format: 'dddd DD MMMM YYYY - HH:mm' });

        $('#min-date').bootstrapMaterialDatePicker({ format: 'DD/MM/YYYY HH:mm', minDate: new Date() });
        // Clock pickers
        $('#single-input').clockpicker({
            placement: 'bottom',
            align: 'left',
            autoclose: true,
            'default': 'now'
        });
        $('.clockpicker').clockpicker({
            donetext: 'Done',
        }).find('input').change(function () {
            console.log(this.value);
        });
        $('#check-minutes').click(function (e) {
            // Have to stop propagation here
            e.stopPropagation();
            input.clockpicker('show').clockpicker('toggleView', 'minutes');
        });
        if (/mobile/i.test(navigator.userAgent)) {
            $('input').prop('readOnly', true);
        }
        // Colorpicker
        $(".colorpicker").asColorPicker();
        $(".complex-colorpicker").asColorPicker({
            mode: 'complex'
        });
        $(".gradient-colorpicker").asColorPicker({
            mode: 'gradient'
        });
        // Date Picker
        jQuery('.mydatepicker, #datepicker').datepicker();
        jQuery('#datepicker-autoclose').datepicker({
            autoclose: true,
            todayHighlight: true
        });
        jQuery('#date-range').datepicker({
            toggleActive: true
        });
        jQuery('#datepicker-inline').datepicker({
            todayHighlight: true
        });
        // Daterange picker
        $('.input-daterange-datepicker').daterangepicker({
            buttonClasses: ['btn', 'btn-sm'],
            applyClass: 'btn-danger',
            cancelClass: 'btn-inverse'
        });
        $('.input-daterange-timepicker').daterangepicker({
            timePicker: true,
            format: 'MM/DD/YYYY h:mm A',
            timePickerIncrement: 30,
            timePicker12Hour: true,
            timePickerSeconds: false,
            buttonClasses: ['btn', 'btn-sm'],
            applyClass: 'btn-danger',
            cancelClass: 'btn-inverse'
        });
        $('.input-limit-datepicker').daterangepicker({
            format: 'MM/DD/YYYY',
            minDate: '06/01/2015',
            maxDate: '06/30/2015',
            buttonClasses: ['btn', 'btn-sm'],
            applyClass: 'btn-danger',
            cancelClass: 'btn-inverse',
            dateLimit: {
                days: 6
            }
        });
    </script>

    }








